# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions CI/CD

on:
  push:
    branches: [ master ]

jobs:
  
  ci-cd-steps:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: ./.github/workflows/build-and-test.yml
      with:
        branch_name: ${{ env.GITHUB_REF }}
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        local-dir: coverage/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}
        # How verbose should the information be - minimal, standard, or verbose
        log-level: standard
