# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  only_build:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - run: npm install --no-optional
    - run: npm test

  build_and_deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - run: npm install --no-optional
    - run: npm test
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        local-dir: coverage/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}
        # How verbose should the information be - minimal, standard, or verbose
        log-level: standard
